FROM python: 3.13.1
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
CMD ["python", "main.py --scrape -s"]


version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["{command_to_run_your_app}"]